version: '3'

services:
    db-fiber:
        image: mysql
        container_name: mysqldb-fiber
        ports:
            - "3306:3306"
        command: --init-file /sql/init.sql
        volumes:
            - ./sql/init.sql:/sql/init.sql            
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_HOST: '%'